version: '3'
services:
  database:
    image: mysql:latest
    container_name: petinder_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=devel
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
